'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PSMSVirtualDeviceManager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _318() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("318", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _355() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("355", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _356() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("356", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _366() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("366", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _369() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("369", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _374() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("374", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _381() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("381", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _441() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("441", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _450() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("450", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _453() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("453", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _466() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("466", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bthci_201_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bthci_201_16x16_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property connect_10101_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect_10101_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property connect_10504_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connect_10504_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_DISPLAY_FAIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_DISPLAY_FAIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_DISPLAY_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_DISPLAY_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_DISPLAY_OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_DISPLAY_OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_DISPLAY_WARN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_DISPLAY_WARN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_HDMI_FAIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_HDMI_FAIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_HDMI_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_HDMI_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_HDMI_OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_HDMI_OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_HDMI_WARN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_HDMI_WARN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_USB_FAIL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_USB_FAIL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_USB_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_USB_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_USB_OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_USB_OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Connection_USB_WARN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Connection_USB_WARN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ControllerAttachments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ControllerAttachments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CustomIMU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomIMU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DevicePairing_6101_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DevicePairing_6101_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DevicePairing_6101_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DevicePairing_6101_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property devmgr_201_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("devmgr_201_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property devmgr_201_48x48_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("devmgr_201_48x48-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dsui_15001_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dsui_15001_16x16_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR1_5504_DIRECT() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR1_5504_DIRECT", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR1_5504_MULTI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR1_5504_MULTI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR1_B403_DIRECT() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR1_B403_DIRECT", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR1_B403_MULTI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR1_B403_MULTI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR2_6A04_DIRECT() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR2_6A04_DIRECT", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EDID_PSVR2_6A04_MULTI() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDID_PSVR2_6A04_MULTI", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exposure_BadBright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exposure_BadBright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exposure_BadDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exposure_BadDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exposure_Good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exposure_Good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exposure_Ref() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exposure_Ref", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Faultrep_5201_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Faultrep_5201_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset1 Segoe UI Symbol;}}
        '''{\colortbl ;\red79\green129\blue189;\red204\green204\blue204;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\sl240\slmult1\b\f0\fs28\lang1031{\pict{\*\picprop}\wmetafile8\picw847\pich847\picwgoal480\pichgoal480 
        '''0100090000034a06000000002106000000000400000003010800050000000b0200000000050000
        '''000c0220002000030000001e000400000007010400040000000701040021060000410b2000cc00
        '''20002000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpControllerAttachments() As String
            Get
                Return ResourceManager.GetString("HelpControllerAttachments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red79\green129\blue189;\red0\green0\blue255;\red0\green0\blue0;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\sa200\sl240\slmult1\cf1\b\f0\fs28\lang7{\pict{\*\picprop}\wmetafile8\picw847\pich847\picwgoal480\pichgoal480 
        '''0100090000034a06000000002106000000000400000003010800050000000b0200000000050000
        '''000c0220002000030000001e0004000000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpDirectModeSteamVR() As String
            Get
                Return ResourceManager.GetString("HelpDirectModeSteamVR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil\fcharset1 Segoe UI Symbol;}{\f3\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red79\green129\blue189;\red204\green204\blue204;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\b\f0\fs28\lang1031{\pict{\*\picprop}\wmetafile8\picw847\pich847\picwgoal480\pichgoal480 
        '''0100090000034a06000000002106000000000400000003010800050000000b0200000000050000
        '''000c0220002000030000001e000400000007010400040 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpRemoteDevices() As String
            Get
                Return ResourceManager.GetString("HelpRemoteDevices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset1 Segoe UI Symbol;}{\f2\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red79\green129\blue189;\red192\green80\blue77;\red204\green204\blue204;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\sl240\slmult1\b\f0\fs28\lang1031{\pict{\*\picprop}\wmetafile8\picw847\pich847\picwgoal480\pichgoal480 
        '''0100090000034a06000000002106000000000400000003010800050000000b0200000000050000
        '''000c0220002000030000001e0004000000070 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpTouchpadShortcuts() As String
            Get
                Return ResourceManager.GetString("HelpTouchpadShortcuts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}}
        '''{\colortbl ;\red79\green129\blue189;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\sl276\slmult1\b\f0\fs28\lang1031{\pict{\*\picprop}\wmetafile8\picw847\pich847\picwgoal480\pichgoal480 
        '''0100090000034a06000000002106000000000400000003010800050000000b0200000000050000
        '''000c0220002000030000001e000400000007010400040000000701040021060000410b2000cc00
        '''2000200000000000200020000000000028000000200000002000000001001800000000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpVirtualMotionTracker() As String
            Get
                Return ResourceManager.GetString("HelpVirtualMotionTracker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset1 Segoe UI Symbol;}{\f2\fnil\fcharset2 Symbol;}}
        '''{\colortbl ;\red79\green129\blue189;\red204\green204\blue204;\red155\green187\blue89;\red192\green80\blue77;}
        '''{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        '''\pard\sl240\slmult1\cf1\b\f0\fs18\lang7{\pict{\*\picprop}\wmetafile8\picw6773\pich6773\picwgoal576\pichgoal576 
        '''0100090000034a80010000002180010000000400000003010800050000000b0200000000050000
        '''000c020001 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpVirtualTracker() As String
            Get
                Return ResourceManager.GetString("HelpVirtualTracker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_34_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_34_16x16_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5302_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5302_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5303_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5303_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5305_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5305_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5315_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5315_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5321_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5321_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5323_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5323_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5332_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5332_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5337_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5337_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5341_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5341_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5345_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5345_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5353_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5353_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5353_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5353_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5364_64x64_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5364_64x64-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mmcshext_128_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mmcshext_128_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mmcshext_128_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mmcshext_128_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netcenter_7_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netcenter_7_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netshell_1607_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netshell_1607_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netshell_1607_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netshell_1607_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netshell_1608_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netshell_1608_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netshell_1608_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netshell_1608_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netshell_1610_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netshell_1610_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property odbcint_1439_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("odbcint_1439_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property odbcint_1439_256x256_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("odbcint_1439_256x256-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pin_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pin_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shell32_16739_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_16739_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shell32_16761_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_16761_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shell32_16762_32x32_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shell32_16762_32x32-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Status_GREEN_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_GREEN_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Status_RED_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_RED_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Status_UNKNOWN_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_UNKNOWN_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Status_WHITE_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_WHITE_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Status_YELLOW_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Status_YELLOW_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Unpin_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unpin_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user32_101_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user32_101_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user32_102_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user32_102_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user32_104_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user32_104_16x16_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wmploc_474_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wmploc_474_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YFlip_Bad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YFlip_Bad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YFlip_Good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YFlip_Good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
